name: my_todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: 15.0.1
  fluttertoast: ^8.2.2
  package_info_plus: ^4.1.0
  permission_handler: ^11.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Comfortaa
      fonts:
#        - asset: fonts/Comfortaa/Comfortaa-Bold.ttf
#        - asset: fonts/Comfortaa/Comfortaa-Light.ttf
#        - asset: fonts/Comfortaa/Comfortaa-Medium.ttf
        - asset: fonts/Comfortaa/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa/Comfortaa-SemiBold.ttf
